// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/tunnel/v1/tunnel.proto

package tunnelv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ClientMessage is sent by the tunnel client.
type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ClientMessage_Register
	//	*ClientMessage_ProxyResponse
	Message       isClientMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_api_tunnel_v1_tunnel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_tunnel_v1_tunnel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_api_tunnel_v1_tunnel_proto_rawDescGZIP(), []int{0}
}

func (x *ClientMessage) GetMessage() isClientMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ClientMessage) GetRegister() *Register {
	if x != nil {
		if x, ok := x.Message.(*ClientMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *ClientMessage) GetProxyResponse() *ProxyResponse {
	if x != nil {
		if x, ok := x.Message.(*ClientMessage_ProxyResponse); ok {
			return x.ProxyResponse
		}
	}
	return nil
}

type isClientMessage_Message interface {
	isClientMessage_Message()
}

type ClientMessage_Register struct {
	Register *Register `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type ClientMessage_ProxyResponse struct {
	ProxyResponse *ProxyResponse `protobuf:"bytes,2,opt,name=proxy_response,json=proxyResponse,proto3,oneof"`
}

func (*ClientMessage_Register) isClientMessage_Message() {}

func (*ClientMessage_ProxyResponse) isClientMessage_Message() {}

// ServerMessage is sent by the tunnel server.
type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ServerMessage_RegisterAck
	//	*ServerMessage_ProxyRequest
	Message       isServerMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_api_tunnel_v1_tunnel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_tunnel_v1_tunnel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_api_tunnel_v1_tunnel_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMessage) GetMessage() isServerMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ServerMessage) GetRegisterAck() *RegisterAck {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_RegisterAck); ok {
			return x.RegisterAck
		}
	}
	return nil
}

func (x *ServerMessage) GetProxyRequest() *ProxyRequest {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_ProxyRequest); ok {
			return x.ProxyRequest
		}
	}
	return nil
}

type isServerMessage_Message interface {
	isServerMessage_Message()
}

type ServerMessage_RegisterAck struct {
	RegisterAck *RegisterAck `protobuf:"bytes,1,opt,name=register_ack,json=registerAck,proto3,oneof"`
}

type ServerMessage_ProxyRequest struct {
	ProxyRequest *ProxyRequest `protobuf:"bytes,2,opt,name=proxy_request,json=proxyRequest,proto3,oneof"`
}

func (*ServerMessage_RegisterAck) isServerMessage_Message() {}

func (*ServerMessage_ProxyRequest) isServerMessage_Message() {}

type Register struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	LocalUrl      string                 `protobuf:"bytes,2,opt,name=local_url,json=localUrl,proto3" json:"local_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Register) Reset() {
	*x = Register{}
	mi := &file_api_tunnel_v1_tunnel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_api_tunnel_v1_tunnel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_api_tunnel_v1_tunnel_proto_rawDescGZIP(), []int{2}
}

func (x *Register) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Register) GetLocalUrl() string {
	if x != nil {
		return x.LocalUrl
	}
	return ""
}

type RegisterAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // if !ok
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAck) Reset() {
	*x = RegisterAck{}
	mi := &file_api_tunnel_v1_tunnel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAck) ProtoMessage() {}

func (x *RegisterAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_tunnel_v1_tunnel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAck.ProtoReflect.Descriptor instead.
func (*RegisterAck) Descriptor() ([]byte, []int) {
	return file_api_tunnel_v1_tunnel_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RegisterAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ProxyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Query         string                 `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyRequest) Reset() {
	*x = ProxyRequest{}
	mi := &file_api_tunnel_v1_tunnel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyRequest) ProtoMessage() {}

func (x *ProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tunnel_v1_tunnel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyRequest.ProtoReflect.Descriptor instead.
func (*ProxyRequest) Descriptor() ([]byte, []int) {
	return file_api_tunnel_v1_tunnel_proto_rawDescGZIP(), []int{4}
}

func (x *ProxyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProxyRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ProxyRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ProxyRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ProxyRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ProxyRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type ProxyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyResponse) Reset() {
	*x = ProxyResponse{}
	mi := &file_api_tunnel_v1_tunnel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyResponse) ProtoMessage() {}

func (x *ProxyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tunnel_v1_tunnel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyResponse.ProtoReflect.Descriptor instead.
func (*ProxyResponse) Descriptor() ([]byte, []int) {
	return file_api_tunnel_v1_tunnel_proto_rawDescGZIP(), []int{5}
}

func (x *ProxyResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProxyResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ProxyResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ProxyResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_api_tunnel_v1_tunnel_proto protoreflect.FileDescriptor

const file_api_tunnel_v1_tunnel_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/tunnel/v1/tunnel.proto\x12\ttunnel.v1\"\x90\x01\n" +
	"\rClientMessage\x121\n" +
	"\bregister\x18\x01 \x01(\v2\x13.tunnel.v1.RegisterH\x00R\bregister\x12A\n" +
	"\x0eproxy_response\x18\x02 \x01(\v2\x18.tunnel.v1.ProxyResponseH\x00R\rproxyResponseB\t\n" +
	"\amessage\"\x97\x01\n" +
	"\rServerMessage\x12;\n" +
	"\fregister_ack\x18\x01 \x01(\v2\x16.tunnel.v1.RegisterAckH\x00R\vregisterAck\x12>\n" +
	"\rproxy_request\x18\x02 \x01(\v2\x17.tunnel.v1.ProxyRequestH\x00R\fproxyRequestB\t\n" +
	"\amessage\"C\n" +
	"\bRegister\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1b\n" +
	"\tlocal_url\x18\x02 \x01(\tR\blocalUrl\"3\n" +
	"\vRegisterAck\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xf0\x01\n" +
	"\fProxyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x14\n" +
	"\x05query\x18\x04 \x01(\tR\x05query\x12>\n" +
	"\aheaders\x18\x05 \x03(\v2$.tunnel.v1.ProxyRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x06 \x01(\fR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc8\x01\n" +
	"\rProxyResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12?\n" +
	"\aheaders\x18\x03 \x03(\v2%.tunnel.v1.ProxyResponse.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012R\n" +
	"\rTunnelService\x12A\n" +
	"\aConnect\x12\x18.tunnel.v1.ClientMessage\x1a\x18.tunnel.v1.ServerMessage(\x010\x01B3Z1github.com/BRAVO68WEB/fwdx/api/tunnel/v1;tunnelv1b\x06proto3"

var (
	file_api_tunnel_v1_tunnel_proto_rawDescOnce sync.Once
	file_api_tunnel_v1_tunnel_proto_rawDescData []byte
)

func file_api_tunnel_v1_tunnel_proto_rawDescGZIP() []byte {
	file_api_tunnel_v1_tunnel_proto_rawDescOnce.Do(func() {
		file_api_tunnel_v1_tunnel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_tunnel_v1_tunnel_proto_rawDesc), len(file_api_tunnel_v1_tunnel_proto_rawDesc)))
	})
	return file_api_tunnel_v1_tunnel_proto_rawDescData
}

var file_api_tunnel_v1_tunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_tunnel_v1_tunnel_proto_goTypes = []any{
	(*ClientMessage)(nil), // 0: tunnel.v1.ClientMessage
	(*ServerMessage)(nil), // 1: tunnel.v1.ServerMessage
	(*Register)(nil),      // 2: tunnel.v1.Register
	(*RegisterAck)(nil),   // 3: tunnel.v1.RegisterAck
	(*ProxyRequest)(nil),  // 4: tunnel.v1.ProxyRequest
	(*ProxyResponse)(nil), // 5: tunnel.v1.ProxyResponse
	nil,                   // 6: tunnel.v1.ProxyRequest.HeadersEntry
	nil,                   // 7: tunnel.v1.ProxyResponse.HeadersEntry
}
var file_api_tunnel_v1_tunnel_proto_depIdxs = []int32{
	2, // 0: tunnel.v1.ClientMessage.register:type_name -> tunnel.v1.Register
	5, // 1: tunnel.v1.ClientMessage.proxy_response:type_name -> tunnel.v1.ProxyResponse
	3, // 2: tunnel.v1.ServerMessage.register_ack:type_name -> tunnel.v1.RegisterAck
	4, // 3: tunnel.v1.ServerMessage.proxy_request:type_name -> tunnel.v1.ProxyRequest
	6, // 4: tunnel.v1.ProxyRequest.headers:type_name -> tunnel.v1.ProxyRequest.HeadersEntry
	7, // 5: tunnel.v1.ProxyResponse.headers:type_name -> tunnel.v1.ProxyResponse.HeadersEntry
	0, // 6: tunnel.v1.TunnelService.Connect:input_type -> tunnel.v1.ClientMessage
	1, // 7: tunnel.v1.TunnelService.Connect:output_type -> tunnel.v1.ServerMessage
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_api_tunnel_v1_tunnel_proto_init() }
func file_api_tunnel_v1_tunnel_proto_init() {
	if File_api_tunnel_v1_tunnel_proto != nil {
		return
	}
	file_api_tunnel_v1_tunnel_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientMessage_Register)(nil),
		(*ClientMessage_ProxyResponse)(nil),
	}
	file_api_tunnel_v1_tunnel_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerMessage_RegisterAck)(nil),
		(*ServerMessage_ProxyRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_tunnel_v1_tunnel_proto_rawDesc), len(file_api_tunnel_v1_tunnel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_tunnel_v1_tunnel_proto_goTypes,
		DependencyIndexes: file_api_tunnel_v1_tunnel_proto_depIdxs,
		MessageInfos:      file_api_tunnel_v1_tunnel_proto_msgTypes,
	}.Build()
	File_api_tunnel_v1_tunnel_proto = out.File
	file_api_tunnel_v1_tunnel_proto_goTypes = nil
	file_api_tunnel_v1_tunnel_proto_depIdxs = nil
}
